/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Risks: () => import('#controllers/risks_controller'),
  Session: () => import('#controllers/session_controller'),
}
