/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ControlFrameworkSchema extends BaseModel {
  static $columns = ['controlId', 'frameworkId', 'id'] as const
  $columns = ControlFrameworkSchema.$columns
  @column()
  declare controlId: number
  @column()
  declare frameworkId: number
  @column({ isPrimary: true })
  declare id: number
}

export class ControlSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'domain', 'frameworks', 'frequency', 'id', 'lastReviewedAt', 'nextReviewAt', 'owner', 'status', 'title', 'updatedAt'] as const
  $columns = ControlSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare domain: string
  @column()
  declare frameworks: string | null
  @column()
  declare frequency: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare lastReviewedAt: DateTime | null
  @column.date()
  declare nextReviewAt: DateTime | null
  @column()
  declare owner: string
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FrameworkSchema extends BaseModel {
  static $columns = ['category', 'compliancePercentage', 'controlsCount', 'createdAt', 'description', 'domainsCount', 'id', 'lastReviewDate', 'name', 'slug', 'status', 'updatedAt', 'version'] as const
  $columns = FrameworkSchema.$columns
  @column()
  declare category: string
  @column()
  declare compliancePercentage: number
  @column()
  declare controlsCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare domainsCount: number
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare lastReviewDate: DateTime | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: string
}

export class RiskSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'frameworks', 'id', 'impact', 'owner', 'probability', 'status', 'title', 'treatment', 'updatedAt'] as const
  $columns = RiskSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare frameworks: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare impact: number
  @column()
  declare owner: string
  @column()
  declare probability: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare treatment: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'sortOrder', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'department', 'email', 'fullName', 'id', 'lastLogin', 'mfaEnabled', 'password', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare department: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLogin: DateTime | null
  @column()
  declare mfaEnabled: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
