/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ControlTransformer from '#transformers/control_transformer'
import type FrameworkTransformer from '#transformers/framework_transformer'
import type RiskTransformer from '#transformers/risk_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Control = InferData<ControlTransformer>
  export namespace Control {
    export type Variants = InferVariants<ControlTransformer>
  }
  export type Framework = InferData<FrameworkTransformer>
  export namespace Framework {
    export type Variants = InferVariants<FrameworkTransformer>
  }
  export type Risk = InferData<RiskTransformer>
  export namespace Risk {
    export type Variants = InferVariants<RiskTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
